# Generated by Django 5.2 on 2025-07-30 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cart',
            new_name='items',
        ),
    ]
